### ISSUE TITLE
Add to quicklisp

### ISSUE THREAD

**Issue by mdbergmann** [cbeo/gtwiwtg#2]
Hi.

This is a nice library.
Don't you want to put it to quicklisp?
That way it would be easier for people to use it in their projects.

**Comment by cbeo** [comment]
I probably should huh?  

I'll look into it.

**Comment by vindarel** [comment]
Thanks in advance. It's a great lib. And please consider Ultralisp too https://ultralisp.org/ adding one's lib there takes three clicks: login with github, add the project, done.

**Comment by cbeo** [comment]
It's in ultralisp now :)

**Comment by cbeo** [comment]
GTWIWTG is now in the December 2020 quicklisp!

**Comment by mdbergmann** [comment]
Cool
