### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mdbergmann** [cbeo/gtwiwtg#3]
Hi there.

The GPL license can practically not be used in commercial products that don't want to release their source code also under GPL.
Is this intentional?

**Comment by cbeo** [comment]
The library is indeed released intentionally under the GPLv3.  

If your business model is unfeasible with a free software product, then I can offer you a private license for a small negotiable fee, or you might try adapting your product to use [series](http://series.sourceforge.net/) or [iterate](https://lispcookbook.github.io/cl-cookbook/iteration.html#iterates-for-loop), both of which provide similar functionality under a non-free license.  

Thanks for taking an interest in the library.

**Comment by mdbergmann** [comment]
That's ok, thanks.
It's completely legit to require a fee for commercial products using an open-source library.

**Comment by cbeo** [comment]
closing for now
