### ISSUE TITLE
[Question] Are lazy squence values memorized?

### ISSUE THREAD

**Issue by GongYiLiao** [cbeo/gtwiwtg#4]
In the code example:  
 ```
> (take 10 (all-primes)) ;; (2 3 5 7 11 13 17 19 23 29) 
```
It seems that the fucntion `all-primes` does not memorize any value after being called (not during being called) as it's a function, not a variable.  Is there a way to define a infinite series as a lazy sequence (such as all non-negative integers) instead of a function using `gtwiwtg`?

**Comment by cbeo** [comment]
Forgive me if I do not quite see what you're asking.  I will proceed here with the assumption that your concern is for the efficiency of the test for primes.

In this case, the test for primes is rather inefficient, and is handled by `prime-p`.  The `all-primes` function, when called, returns an object - an instance of the class `generator!`.  Each time we call `all-primes` a new lazy sequence is created.  Values are not produced until we pass the sequence to a "consuming form" like `take`.    

Breaking the example up a little might help to clarify:

```lisp

(let ((prime-generator (all-primes)))
   (print prime-generator)           ;; #<GTWIWTG::THUNK-BACKED-GENERATOR! {1002899AF3}> 
   (take 10 prime-generator))      ;; (2 3 5 7 11 13 17 19 23 29)

```

Internally the `prime-generator` object above keeps track of its own internal state. 

The library has been written so that you cannot pass the same generator to two different consuming forms.  E.g. the following will fail:

```lisp

(let ((prime-generator (all-primes)))
   (print prime-generator)           ;; #<GTWIWTG::THUNK-BACKED-GENERATOR! {1002899AF3}> 
   (take 10 prime-generator)      ;; (2 3 5 7 11 13 17 19 23 29)
   (take 2 prime-generator) )      ;; ERROR!  cannot use a generator after it has been consumed..

```

If you wanted to take advantage of memoization in the generation of primes, you would do so by re-writing the `prime-p` function to cache values.   But this may not even be your concern. If I have misunderstood your question, please let me know.

**Comment by GongYiLiao** [comment]
I can only come up with an ugly and side-effect ridden `prime-p` relpacement:

```
;; initial prime number list 
(defparameter *prime-store* '(2))
;; test if n is a prime, if so, add to the end of *prime-store*
(defun prime-p-2 (n)
  (let ((is-prime (or (and (<= n (car (last prime-store))) (position n prime-store))
		      (loop :for x :from (car (last prime-store)) :upto (sqrt n)
			    :when (zerop (mod n x)) :do (return nil)
			      :finally (return t)))))
    (when is-prime (setf *prime-store* (append *prime-store* (list n))))
    is-prime))
;; generator for upcoming primes 
(defun next-primes ()
  "Creates a generator that produces an infinite series of primes."
  (filter! #'prime-p-2 (range :from (car (last *prime-store*)) )))
;;
(defun take-more-primes (n)
  "Only for Side-effect"
  (progn (take n (next-primes)))
  (print *prime-store*))
;;
(take-more-primes 100)
;; (2 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101
;;  103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197
;;  199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311
;;  313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431
;;  433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 547)

```

But above code, particularly the `prime-p-2`  function, rely on a strong assumption: `*prime-store*` contains all the known prime numbers smaller than `n` therefore the we can kick off the `loop` statement  from the last element of *prime-store* ratherr than `2`. 

Not sure if this makes sense under `gtwiwtg`'s design.

**Comment by cbeo** [comment]
One way you might do it is to define a new subclass of `gtwiwtg::generator!` that wraps a real generator and keeps a cache of already generated values.   Here's one approach:

``` lisp
(defpackage :primegen
  (:use :cl :gtwiwtg))

(defun prime-p (n)
  "Naive test for primes."
  (loop
    :for x :from 2 :upto (sqrt n)
    :when (zerop (mod n x)) :do (return nil)
      :finally (return t)))

(defclass recycling-prime-generator (gtwiwtg::generator!)
  ((store :initform (list 2) :initarg :store :accessor prime-store)
   (real-generator :initform nil :accessor prime-generator)))

(defmethod initialize-instance :after ((gen recycling-prime-generator) &key)
  (let* ((new-primes
           (filter! 'prime-p
                    (range :from (1+ (car (prime-store gen))))))
         
         (cached-new-primes
           (map! (lambda (p) (push p (prime-store gen)) p)
                 new-primes))
         
         (old-primes
           (seq (reverse (prime-store gen)))))
    
    (setf (prime-generator gen)
          (concat! old-primes cached-new-primes))))

(defun recycle (gen)
  "Accepts an instance of RECYCLING-PRIME-GENERATOR and returns a new
  generator that pickus up where its argument left off."
  (make-instance 'recycling-prime-generator
                 :store (slot-value gen 'store)))

(defmethod gtwiwtg::has-next-p ((gen recycling-prime-generator))
  (gtwiwtg::has-next-p (slot-value gen 'real-generator)))

(defmethod gtwiwtg::next ((gen recycling-prime-generator))
  (gtwiwtg::next (slot-value gen 'real-generator)))

(defmethod gtwiwtg::stop :after ((gen recycling-prime-generator))
  (gtwiwtg::stop (slot-value gen 'real-generator)))

(defun all-primes (&optional gen)
  (if gen (recycle gen)
      (make-instance 'recycling-prime-generator)))
```

To use it you'd do something like

```  lisp
(defvar *primes* (all-primes))
(take 20 *primes*)
(setf *primes* (recycle *primes*))  ;; copies the list of already-generated primes to the new generator
(take 30 *primes*)                         ;; uses the already-generated primes first, then proceeds to generate new ones
```


(While investigating this issue I actually discovered a bug in `filter!`. So the example above will not run correctly using the quicklisp version. But the most recent version from this repo should work.)
